Closes #4 - Upload image for foods
gurungrahul2/FoodShala pull request #7
Opened 2019-05-01 03:26 UTC by tadeubarbosa

### The functionality for upload image for food.

*This one need to be revised!*

I was not think about frontend things, like these comments on #6 are talking.
For example, the image is just putted in the `HTML`:

![image](https://user-images.githubusercontent.com/4499999/57004672-22426d80-6ba7-11e9-87df-146de23c772e.png)

...

![image](https://user-images.githubusercontent.com/4499999/57004686-3d14e200-6ba7-11e9-8ea2-44f92719f934.png)

2019-05-01 05:22 UTC, gurungrahul2 commented
@tadeubarbosa Thanks for PR, I will have a look shortly.

2019-05-02 06:09 UTC, rahgurung requested changes
PTAL at comments.

2019-05-02 06:09 UTC, gurungrahul2 commented on application/models/Food_model.php
> +
@tadeubarbosa Can you please use 2 spaces as indentation.

2019-05-02 06:09 UTC, gurungrahul2 commented on application/views/foods/add_menu.php
> +	</div>
same here.

2019-05-02 06:09 UTC, gurungrahul2 commented on application/views/foods/index.php
> +	<?php
same here.

2019-05-02 12:28 UTC, tadeubarbosa commented
Ok! Done!

2019-05-05 09:43 UTC, gurungrahul2 commented
Hey, @tadeubarbosa actually @henriquepesi has implemented the card structure for foods UI, can you adapt it to the front end too, it's just a basic wiring and please resolve the conflicts :)

2019-05-05 21:01 UTC, tadeubarbosa commented
I was merge that! :slightly_smiling_face:

2019-05-24 09:42 UTC, rahgurung requested changes

2019-05-24 09:42 UTC, rahgurung commented on application/models/Food_model.php
> +        $data['image'] = "assets/img/" . $filename;
I think we should make a separate folder inside `img` called uploads and keep all our images there because later when I will implement other features which will need images, it is going to be unmanageable, so having a separate folder for everything will be more efficient.

2019-05-25 01:31 UTC, tadeubarbosa commented on application/models/Food_model.php
> +        $data['image'] = "assets/img/" . $filename;
Yes, we can do that! Really will be hard to work like this.

2019-05-25 01:34 UTC, tadeubarbosa commented on application/models/Food_model.php
> +        $data['image'] = "assets/img/" . $filename;
`assets/upload` or `assets/img/upload`? :thinking:

2019-05-26 05:32 UTC, gurrrung commented on application/models/Food_model.php
> +        $data['image'] = "assets/img/" . $filename;
I prefer the later.

2019-05-26 12:13 UTC, gurrrung commented
Image upload is not working, please check it, after changing the path you need to make some more changes too. @tadeubarbosa

2019-05-26 12:16 UTC, rahgurung requested changes
Please check the comments I left and update your .gitkeep inside img folder too too.

2019-05-26 12:16 UTC, gurrrung commented on application/models/Food_model.php
> +        'upload_path'   => './assets/img/upload/',
It should be uploads here too.

2019-05-26 12:16 UTC, gurrrung commented on application/views/foods/index.php
> +				if($food['image'] !==null ) {
add a space between !== and null

2019-05-26 12:16 UTC, gurrrung commented on foodshala.sql
> +  `image` varchar(245) DEFAULT NULL,
we don't need comma by the end of this line.

2019-05-27 15:04 UTC, rahgurung approved these changes

2019-05-27 15:05 UTC, gurrrung commented
Thanks :)

2019-05-27 15:05 UTC, merged